services:
  postgres:
    image: postgres:latest
    container_name: leaderboard-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: player-leaderboard
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  leaderboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leaderboard
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DB_NAME: player-leaderboard
      JWT_SECRET: some_random_secret_code

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
